# Generated by Django 6.0.3 on 2026-03-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='A beautiful cultural artifact.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='https://placehold.co/400x300/png?text=Artifact', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='artifacts.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('materials', models.CharField(max_length=300)),
                ('cultural_significance', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='artifacts.artifact')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['artifact'],
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(blank=True, default='https://placehold.co/400x300/png?text=Villa', max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villas', to='artifacts.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='villa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='artifacts.villa'),
        ),
    ]
