# Generated by Django 6.0.3 on 2026-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='embedding',
            field=models.JSONField(blank=True, help_text='MobileNetV2 feature vector (auto-generated)', null=True),
        ),
    ]
