# Generated by Django 5.2.4 on 2026-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Direct URL to a 400x300 image, or local path like assets/images/villa_1.jpg",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="villa",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Standard 400x300 image URL or local path.",
                max_length=500,
                null=True,
            ),
        ),
    ]
