# Generated by Django 6.0.3 on 2026-04-01 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


def generate_unique_qr_codes(apps, schema_editor):
    """Assign unique UUIDs to existing villas."""
    Villa = apps.get_model('artifacts', 'Villa')
    for villa in Villa.objects.all():
        villa.qr_code = uuid.uuid4()
        villa.save(update_fields=['qr_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_artifact_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.URLField(blank=True, default='', help_text='URL to audio narration file', max_length=500),
        ),
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(default='en', help_text='Language code (en, am, fr, ar, sw)', max_length=10),
        ),
        migrations.AddField(
            model_name='villa',
            name='cultural_highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of cultural highlight strings'),
        ),
        migrations.AddField(
            model_name='villa',
            name='design_philosophy',
            field=models.TextField(blank=True, default='', help_text='Explanation of villa architecture and decor'),
        ),
        # Step 1: Add qr_code WITHOUT unique constraint
        migrations.AddField(
            model_name='villa',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for QR code scanning'),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_qr_codes, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name='villa',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for QR code scanning', unique=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='welcome_story',
            field=models.TextField(blank=True, default='', help_text='Narrative welcome text for guests'),
        ),
        migrations.CreateModel(
            name='VillaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within villa')),
                ('description', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='', help_text='Story-format guide text for this section')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='artifacts.villa')),
            ],
            options={
                'ordering': ['villa', 'order'],
                'unique_together': {('villa', 'order')},
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Room/zone where this artifact is displayed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='artifacts.villasection'),
        ),
    ]
