# Generated by Django 6.0.3 on 2026-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_story_audio_url_story_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='image_url',
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villas/'),
        ),
    ]
