# Generated by Django 6.0.3 on 2026-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_villa_qr_image_villa_slug'),
    ]

    operations = [
    ]
