# Generated by Django 6.0.3 on 2026-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_alter_villa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Featured Artifacts on home screen'),
        ),
    ]
