# Generated by Django 6.0.3 on 2026-03-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The uploaded image that was scanned.', upload_to='scans/')),
                ('result_object', models.CharField(help_text='The artifact name returned by the AI.', max_length=300)),
                ('result_country', models.CharField(help_text='The country of origin returned by the AI.', max_length=100)),
                ('result_category', models.CharField(default='Other', help_text='The category returned by the AI.', max_length=100)),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence score (0.0 to 1.0).')),
                ('story_generated', models.BooleanField(default=False, help_text='Whether a new story was AI-generated for this scan.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the scan failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_artifact', models.ForeignKey(blank=True, help_text='The DB artifact this scan matched to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='artifacts.artifact')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
